### ISSUE TITLE
Should be possible to report Waterfox Classic bug through Waterfox Classic

### ISSUE THREAD

**Issue by powerbroker** [WaterfoxCo/Waterfox#2302]
### What happened?

Waterfox bugs are managed within Github, and Github does not support Waterfox classic. So, a user who discovered a bug in Waterfox Classic is unable to report it, leaving developers unaware about the issue. E.g. Waterfox 2021.09, which is "Firefox/68.0 Waterfox/56.6.2021.09" is not supported by Github, and Github doesn't work properly in it.

There should be a way to report Waterfox release bug with this waterfox release or any common tool such as e-mail client. With no need to install other browsers for just reporting Waterfox bugs.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G3.𝑋 (Current)

### What platform are you seeing the problem on?

Windows

**Comment by powerbroker** [comment]
> You can still report that on reddit or on GitHub by using Polly extension.

Wow! there is a reddit thread https://www.reddit.com/r/waterfox/

BTW gooogling "report Waterfox bug" return following obsolete thread, suggesting to use Github: https://www.reddit.com/r/waterfox/comments/c6iay2/how_to_report_bug_to_developer/

Goooogling "Github Polly extension" returns https://github.com/App-vNext/Polly 
Is this right Polly to deal with bug tracking of Github?

**Comment by hawkeye116477** [comment]
> Is this right Polly to deal with bug tracking of Github?

No, here is https://github.com/WaterfoxCo/Waterfox/blob/classic/browser/extensions/zakius%40polly.xpi. After installing it, you need to go to GH and then click on extension icon and choose „use request modification” and „webcomponents-bundle”.

**Comment by powerbroker** [comment]
Thx!
