### ISSUE TITLE
DRM (Digital Rights Management) 

### ISSUE THREAD

**Issue by wbak1102** [WaterfoxCo/Waterfox#2467]
It does not work in G4.0.3.1 DRM (Digital Rights Management) ?
Version G3.2.6 is OK

**Comment by MrAlex94** [comment]
Unsure why Widevine `4.10.2209.1` is misbehaving on certain platforms, but commmit https://github.com/mozilla/gecko-dev/commit/d913610f657c2345daacf32785b0a1e185f45575 should fix the issue. It's currently sitting in my local repo and will be available with the next release due in a few days.

Please re-open once you've updated (when available) if it still occurs.
