### ISSUE TITLE
The add-on does not work

### ISSUE THREAD

**Issue by wbak1102** [WaterfoxCo/Waterfox#2726]
### What happened?

The add-on does not work !    https://github.com/p1usminus/roomybookmarksredux/releases
Roomy Bookmarks Toolbar redux
in G4.1.2.1 it was OK

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by thunderstone135** [comment]
It appears that Addons using Bootstrap suddenly stopped working on G4.1.3.
Even TabMixPlus stopped working when I updated to G4.1.3.

**Comment by thunderstone135** [comment]
@wbak1102 you can probably try the fix mentioned in https://github.com/WaterfoxCo/Waterfox/issues/2725#issuecomment-1165181692.
I'm not sure if it will work for you, so you should probably backup your Waterfox Folder just in case.

**Comment by adamp01** [comment]
Hey guys, I've verified the fix suggested by onemen resolves the issue for Roomy as well. I'm pushing the fix now and will release a new build in the next few hours.

**Comment by wbak1102** [comment]
Broke G4.1.3

**Comment by adamp01** [comment]
@wbak1102 - resolved as of G4.1.3.1. Available now in Releases and will be pushing update in a few minutes.
