### ISSUE TITLE
Installer should warn user about running on unsupported - intel Atom - CPU

### ISSUE THREAD

**Issue by powerbroker** [WaterfoxCo/Waterfox#2776]
### What happened?

install Waterfox(G4 1.4) on intel Atom N2600(under Win7x64)
installation succeeds, but Waterfox itself crashes on start. at the same time, it runs fine under Win7x64 on i5 CPU.

intel Atom sucks(4GB RAM max), so it may has no sense to fix Waterfox crash on it. a good alternative - Firefox x64 - is available and works on Atom N2600 more or less.

but a warning message in installer, saying: "Atom CPU is not supported, so use at your own risk" would look professional

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G4

### What platform are you seeing the problem on?

Windows

**Comment by MrAlex94** [comment]
This has been fixed in the G5 of Waterfox.
