### ISSUE TITLE
Updates Regarding Android?

### ISSUE THREAD

**Issue by shubh402** [WaterfoxCo/Waterfox#2848]
it's been years and years since we are requesting waterfox Android version is it every gonna come?

**Comment by surapunoyousei** [comment]
![image](https://user-images.githubusercontent.com/73892113/194802898-a984389f-abab-48ed-b9e0-e83e010e6999.png)

**Comment by surapunoyousei** [comment]
> > It looks like it's pending approval from Google. It may be Google's mood when it comes :(
> > ![image](https://user-images.githubusercontent.com/73892113/194802898-a984389f-abab-48ed-b9e0-e83e010e6999.png)
> 
> And why they should ask the approval of Google, why they don't upload it on github or f-droid?

Maybe there is a reason. Google tends to dislike open source web browsers, so I understand that the play store is not approved, but it is unclear why the binary is not published.

It is almost certain that it will be a web browser based on MPL 2.0, so if you look at the fact that Waterfox does not publish the source code, it may not have happened.
