### ISSUE TITLE
Baldi's Basics, Granny PC Version and Hello Neighbor on Windows Vista

### ISSUE THREAD

**Issue by Saswat2005** [WaterfoxCo/Waterfox#3006]
Can you please run these three games on Windows Vista Extended Kernel:-

1. Baldi's Basics in Education and Learning
2. Granny PC Version
3. Hello Neighbor

**Comment by jobbautista9** [comment]
Vista is not supported, and hasn't been for a long time. You're on your own.

**Comment by Saswat2005** [comment]
Can I run these three games on Windows Vista Extended Kernel?

**Comment by MrAlex94** [comment]
Hi! These don't look like web based games, but rather Windows applications? Think this may be the wrong place for this :)
