### ISSUE TITLE
Widevine ?

### ISSUE THREAD

**Issue by wbak1102** [WaterfoxCo/Waterfox#3133]
### What happened?

A bug happened!

### Reproducible?

- [X] I have tested this on Firefox.

### Version

G5

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
Widevine still doesn't work G5.1.12
```

**Comment by wbak1102** [comment]
Netflix, Amazon Prime is the same.

**Comment by MrAlex94** [comment]
Seems to work for me!
![image](https://github.com/WaterfoxCo/Waterfox/assets/4728920/f6ef0dbd-a1af-41d5-bae4-fa3e3ef5a8f3)
Guess we need to test out what's going on in your system.
Could you go to `about:plugins` and list what's there?
Could you also go to `about:support`, click `Copy text to clipboard` and paste it here?

**Comment by wbak1102** [comment]
Everything works in Firefox 115.2.0esr

**Comment by MrAlex94** [comment]
I'm not sure what to say, I've asked quite a few users and Widevine works without issue for them.
I've tested myself as well on 3 separate Windows devices I could get my hands on, and they all work.

This is just as frustrating for me, as it is for you, but I'm not sure there's much I can do in the way of helping.

I'll close this as a `can't repro`.
