### ISSUE TITLE
[Android] enable using desktop add-ons

### ISSUE THREAD

**Issue by nofishonfriday** [WaterfoxCo/Waterfox#3308]
Hi,

first of all, very happy to see Waterfox for Android happening, thank you, and sorry for posting here as the [Android repo](https://github.com/WaterfoxCo/Waterfox-Android) doesn't seem to have 'Issues' enabled.

My FR/suggestion: There are [not many](https://addons.mozilla.org/en-US/android/) official add-ons for Firefox Android available currently, but there's a [workaround](https://www.androidpolice.com/install-add-on-extension-mozilla-firefox-android/) to also use FF desktop version add-ons, but it's a bit tedious and involves needing a FF account. Could this 'workaround' be (optionally) enabled on WF for Android so it's possible to use desktop add-ons out of the box?

**Comment by nofishonfriday** [comment]
edit:
If I understand correctly this will work if #3284 is implemented, so feel free to close this in case.

**Comment by MrAlex94** [comment]
On a technical level, this is now done.

Problem is, Mozilla redirect on the homepage and grey out the button for allowing you to install Desktop apps specifically. But there are over 500 add-ons or so on the Android store, which is a big improvement.

If you do a general user agent override, then you can install any add-on your heart desires! I've been umming and ahing about maybe overriding the UA for AMO, but feel like long term that may cause issues. I'll close the issue, but feel free to comment regarding the UA override.

Slightly different from the other bug than sideloading.

**Comment by nofishonfriday** [comment]
Thank you for implementing this!

> I've been umming and ahing about maybe overriding the UA for AMO, but feel like long term that may cause issues. I'll close the issue, but feel free to comment regarding the UA override.

I think if Waterfox allows overriding the UA for AMO it shouldn't be enabled by default, rather a user setting witha warning, so users are aware they install potentially incompatible add ons.
